apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-deployment
  namespace: mongodb-namespace
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_SITE_BASEURL
              value: /mongodbexpress/
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://admin:password@10.200.39.85:30017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: mongodb-namespace
spec:
  selector:
    app: mongodb-express
  # type: LoadBalancer # Uncomment for external service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      # nodePort: 30000 # Uncomment for external service
