apiVersion: v1
data:
  config.yml: |-
        modules:
              default:
                      # These settings are used if no module is specified, the
                      # specified module doesn't exist, or of course if
                      # module=default is specified.
                      user: "sysadmin"
                      pass: "P@ssw0rd"
                      # The below settings correspond to driver-type, privilege-level, and
                      # session-timeout respectively, see `man 5 freeipmi.conf` (and e.g.
                      # `man 8 ipmi-sensors` for a list of driver types).
                      driver: "LAN_2_0"
                      privilege: "user"
                      # The session timeout is in milliseconds. Note that a scrape can take up
                      # to (session-timeout * #-of-collectors) milliseconds, so set the scrape
                      # timeout in Prometheus accordingly.
                      # Must be larger than the retransmission timeout, which defaults to 1000.
                      timeout: 10000
                      # Available collectors are bmc, ipmi, chassis, dcmi, sel, and sm-lan-mode
                      # If _not_ specified, bmc, ipmi, chassis, and dcmi are used
                      collectors:
                      - bmc
                      - ipmi
                      - chassis
                      # Got any sensors you don't care about? Add them here.
                      exclude_sensor_ids:
                      - 2
                      - 29
                      - 32
                      - 50
                      - 52
                      - 55
              dcmi:
                      # Use these settings when scraped with module=dcmi.
                      user: "sysadmin"
                      pass: "P@ssw0rd"
                      privilege: "admin"
                      driver: "LAN_2_0"
                      collectors:
                      - dcmi
              thatspecialhost:
                      # Use these settings when scraped with module=thatspecialhost.
                      user: "sysadmin"
                      pass: "P@ssw0rd"
                      privilege: "admin"
                      driver: "LAN"
                      collectors:
                      - ipmi
                      - sel
                      # Need any special workaround flags set? Add them here.
                      # Workaround flags might be needed to address issues with specific vendor implementations
                      # e.g. https://www.gnu.org/software/freeipmi/freeipmi-faq.html#Why-is-the-output-from-FreeIPMI-different-than-another-software_003f
                      # For a full list of flags, refer to:
                      # https://www.gnu.org/software/freeipmi/manpages/man8/ipmi-sensors.8.html#lbAL
                      workaround_flags:
                      - discretereading
                      # If you require additional command line arguments (e.g. --bridge-sensors for ipmimonitoring),
                      # you can specify them per collector - BE CAREFUL, you can easily break the exporter with this!
                      custom_args:
                              ipmi:
                              - "--bridge-sensors"
              advanced:
                      # Use these settings when scraped with module=advanced.
                      user: "sysadmin"
                      pass: "P@ssw0rd"
                      privilege: "admin"
                      driver: "LAN"
                      collectors:
                      - ipmi
                      - sel
                      # USING ANY OF THE BELOW VOIDS YOUR WARRANTY! YOU MAY GET BITTEN BY SHARKS!
                      # You can override the command to be executed for a collector. Paired with
                      # custom_args, this can be used to e.g. execute the IPMI tools with sudo:
                      collector_cmd:
                              ipmi: sudo
                              sel: sudo
                      custom_args:
                              ipmi:
                              - "ipmimonitoring"
                              sel:
                              - "ipmi-sel"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ipmi-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.6.1
  name: ipmi-exporter-configuration
  namespace: monitoring
