kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  nfs:
    server: 10.200.39.3
    path: /storage/prometheus
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-prometheus

